/**
 * GitHub PR comment reporter — Markdown output.
 *
 * Generates a markdown table suitable for posting as a PR comment.
 */

import type { AnalysisResult, CheckResult } from '../types.js';
import { RiskLevel } from '../types.js';

function riskEmoji(risk: RiskLevel): string {
  switch (risk) {
    case RiskLevel.SAFE: return ':white_check_mark:';
    case RiskLevel.LOW: return ':large_blue_circle:';
    case RiskLevel.MEDIUM: return ':warning:';
    case RiskLevel.HIGH: return ':red_circle:';
    case RiskLevel.CRITICAL: return ':rotating_light:';
  }
}

function blocksStr(check: CheckResult): string {
  const parts: string[] = [];
  if (check.blocks.reads) parts.push('reads');
  if (check.blocks.writes) parts.push('writes');
  if (check.blocks.otherDdl) parts.push('DDL');
  return parts.join(', ') || 'none';
}

export function reportGitHub(results: AnalysisResult[]): string {
  const lines: string[] = [];
  lines.push('## pgfence Migration Safety Report');
  lines.push('');

  for (const result of results) {
    const emoji = riskEmoji(result.maxRisk);
    lines.push(`### \`${result.filePath}\` ${emoji} ${result.maxRisk}`);
    lines.push('');

    // Extraction warnings
    if (result.extractionWarnings && result.extractionWarnings.length > 0) {
      for (const w of result.extractionWarnings) {
        lines.push(`> :warning: **${w.message}** (\`${w.filePath}:${w.line}:${w.column}\`)`);
      }
      lines.push('');
    }

    // Statement checks
    if (result.checks.length > 0) {
      lines.push('| # | Statement | Lock Mode | Blocks | Risk | Message |');
      lines.push('|---|-----------|-----------|--------|------|---------|');
      for (let i = 0; i < result.checks.length; i++) {
        const c = result.checks[i];
        const effectiveRisk = c.adjustedRisk ?? c.risk;
        const riskStr = c.adjustedRisk
          ? `${riskEmoji(effectiveRisk)} ${effectiveRisk} (was ${c.risk})`
          : `${riskEmoji(effectiveRisk)} ${effectiveRisk}`;
        // Escape pipes in preview
        const preview = c.statementPreview.replace(/\|/g, '\\|');
        const msg = c.message.replace(/\|/g, '\\|');
        lines.push(`| ${i + 1} | \`${preview}\` | ${c.lockMode} | ${blocksStr(c)} | ${riskStr} | ${msg} |`);
      }
      lines.push('');

      // Safe rewrite recipes
      const rewrites = result.checks.filter((c) => c.safeRewrite);
      if (rewrites.length > 0) {
        lines.push('<details>');
        lines.push('<summary>Safe Rewrite Recipes</summary>');
        lines.push('');
        for (const c of rewrites) {
          lines.push(`#### \`${c.ruleId}\`: ${c.safeRewrite!.description}`);
          lines.push('```sql');
          for (const step of c.safeRewrite!.steps) {
            lines.push(step);
          }
          lines.push('```');
          lines.push('');
        }
        lines.push('</details>');
        lines.push('');
      }
    } else {
      lines.push(':white_check_mark: No dangerous statements detected.');
      lines.push('');
    }

    // Policy violations
    if (result.policyViolations.length > 0) {
      lines.push('**Policy Violations:**');
      lines.push('');
      lines.push('| Severity | Rule | Message | Suggestion |');
      lines.push('|----------|------|---------|------------|');
      for (const v of result.policyViolations) {
        const sev = v.severity === 'error' ? ':red_circle: error' : ':warning: warning';
        const msg = v.message.replace(/\|/g, '\\|');
        const sug = v.suggestion.replace(/\|/g, '\\|');
        lines.push(`| ${sev} | \`${v.ruleId}\` | ${msg} | ${sug} |`);
      }
      lines.push('');
    }
  }

  // Coverage summary (Trust Contract requirement)
  const totalStatements = results.reduce((sum, r) => sum + r.statementCount, 0);
  const dynamicWarnings = results.reduce(
    (sum, r) => sum + (r.extractionWarnings?.length ?? 0),
    0,
  );
  const coveragePct = totalStatements > 0
    ? Math.round(((totalStatements - dynamicWarnings) / totalStatements) * 100)
    : 100;
  lines.push('### Coverage');
  lines.push('');
  lines.push(
    `Analyzed **${totalStatements}** SQL statements. ` +
    `**${dynamicWarnings}** dynamic statements not analyzable. ` +
    `Coverage: **${coveragePct}%**`,
  );
  lines.push('');

  lines.push('---');
  lines.push('*Generated by [pgfence](https://github.com/pgfence/pgfence)*');

  return lines.join('\n');
}
